#index:
#    path: /
#    controller: App\Controller\DefaultController::index

delivery:
  path: /delivery
  controller: App\Controller\DeliveryEstimationController::index

delivery_estimation:
  path: /delivery/estimation
  controller: App\Controller\DeliveryEstimationController::getEstimatedDeliveryDate
